### PR TITLE
Added vertical tree view

### PR DESCRIPTION
**Pull request by JPJPJPOPOP**
- Added vertical tree view.
- Tree view requires graph to have a root and contain no cycles
- Display warning when switching to tree view when the above conditions aren't met

### CODE REVIEW

**Comment by ftyers** [comment]
@jonorthwash how about we merge this?

**Comment by jonorthwash** [comment]
> @jonorthwash how about we merge this?

I don't think we've tested it, but besides that, I have no objections.

**Comment by ftyers** [comment]
If we merge it we'll be able to test it on your page right?

**Comment by jonorthwash** [comment]
That's not usually how testing is supposed to work, but yes, that might be easiest here.  Hopefully it won't break things for anyone.

**Pull request merged**
