### PR TITLE
Merging UD changes

### PR DESCRIPTION
**Pull request by MidasDoas**
#25 #24 #23 #15 #9

### CODE REVIEW

**Comment by jonorthwash** [comment]
This seems to cause things not to work at all anymore for me.  Could someone else check?

**Comment by MidasDoas** [comment]
I confirm that jonorthwash.github.io/visualise.html doesn't seem to work at all, which is confusing because everything works on midasdoas.github.io/visualise.html and they should be up to date with each other. Moreover, even if they are out of sync, they would be out of sync only in that yours doesn't do URL decoding, and it doesn't seem plausible that that would be the cause of everything breaking.

**Comment by jonorthwash** [comment]
I can't seem to get yours to work either..?

**Comment by MidasDoas** [comment]
That's bizarre. I still can
screen shot 2017-05-29 at 12 53 31 pm
screen shot 2017-05-29 at 12 53 48 pm
screen shot 2017-05-29 at 12 55 00 pm

**Comment by jonorthwash** [comment]
Ah!  Okay, there are four repos here:
# https://github.com/jonorthwash/ud-annotatrix/ - the main one
# https://github.com/jonorthwash/jonorthwash.github.io/ - where it's primarily hosted
# https://github.com/midasdoas/ud-annotatrix/ - your main repo
# https://github.com/midasdoas/midasdoas.github.io/ - where you host yours

The first three are all in sync.  The pull request was from your main repo to my main repo, and I pushed the changes to where I host it.  But it the last one, where you host it, has updates that are incompatible with the others.  I have all four as remotes locally, and it's refusing to pull from the last one.

**Comment by jonorthwash** [comment]
So what you should do now, @MidasDoas, is synchronise your two repos, resolving any conflicts, and send another pull request.

**Comment by MidasDoas** [comment]
Done

**Comment by jonorthwash** [comment]
I mean you should send the pull request to this repo...

**Pull request merged**
