### PR TITLE
Punctuation Annotation

### PR DESCRIPTION
**Pull request by mr-martian**
This more or less covers issue #265.

When a user presses "p" it goes through the tree and finds all the punctuation.

For anything it's able to pair it looks for nodes between the two that have heads that aren't between them. If it finds any it attaches the punctuation both the left-most node, if possible, and the left-most and right-most respectively if not. If it doesn't find any it does the same with nodes that have no heads.

For anything not paired (either mismatched or not in the list of paired punctuation) it finds the nearest connection on either side whose endpoints are on different sides of the punctuation. It then does the same thing for each node in that range. Any node for which the range doesn't include the punctuation can't be attached to without breaking projectivity.
If the punctuation is the last node in the sentence and the root is accessible it attaches to that. If the bounding arc is "conj" it attaches to the node on the right.
The remaining nodes are sorted by distance, preferring ones on the left. If any of the possible nodes has a deprel in `["acl", "advcl", "amod", "appos", "ccomp", "obl"]` (var commaEaters) then the nearest one is attached to. If it's still not attached it just picks the nearest available node.

### CODE REVIEW

**Comment by jonorthwash** [comment]
> When a user presses "p" it goes through the tree and finds all the punctuation.

For the whole corpus or for the given sentence?

**Comment by jonorthwash** [comment]
There's a [python implementation of similar functionality](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/fixpunct.py) that I just learned about.

**Comment by jonorthwash** [comment]
> It applies only to the current tree.

I think that's probably the behaviour we want.  Otherwise things you can't see might be updated, and you wouldn't see it.  That'd be undesirable, I think.

> Anything already connected by "punct" that isn't PUNCT is marked as such. Existing connections may be replaced, though I could change that fairly easily.

Okay, so if I understand right, anything that has a `punct` relation is updated (if the algorithm wants it to be somewhere different)?  I think that's what we want.  And anything that has a POS tag `PUNCT` gets the `PUNCT` POS tag?  Also good.  And I guess anything with POS tag `PUNCT` gets associated per the algorithm even if not already associated?

**Comment by mr-martian** [comment]
I misremembered. Anything with a `punct` relation and no POS tag is labeled `PUNCT` and the algorithm tries to connect anything with POS tag `PUNCT` even if it's already connected (which I can change).

**Comment by jonorthwash** [comment]
That sounds like what I understood, and also like what we want :D

**Pull request merged**
