### PR TITLE
Added upload button and progress bar for upload.

### LINKED ISSUE #19: Loading button and progress indicator
Instead of just automatically starting to upload when a file is chosen, have a button that says "upload" (or "load"). There should also be some indicator showing the progress of the upload.

### PR DESCRIPTION
**Pull request by JPJPJPOPOP**
Fixes #19.

Before uploading:
screen shot 2018-01-13 at 10 03 03 pm

After uploading:
screen shot 2018-01-13 at 10 03 21 pm

### CODE REVIEW

**Comment by ftyers** [comment]
That wasn't what I meant by progress bar, but I guess it could be interesting, what do you think @maryszmary and @jonorthwash ?

**Comment by JPJPJPOPOP** [comment]
> There should also be some indicator showing the progress of the upload.

@ftyers The progress bar is for the upload, i.e. it goes up as the upload completes. I thought that was what you meant?

**Comment by jonorthwash** [comment]
Yeah, this is a different issue that @JPJPJPOPOP is fixing, @ftyers.  I'll test it out.

**Comment by jonorthwash** [comment]
Okay, a couple issues.

1. progress bar at bottom of screen makes the window too wide (chromium):



2. Seems to upload before you click "upload"?  The "upload" and "close" buttons seem to do the same thing?

**Comment by jonorthwash** [comment]
Perhaps it would also be good to have two different modes: "append to currently loaded data" or "replace currently loaded data"?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash 
> progress bar at bottom of screen makes the window too wide (chromium):
I didn't create that, it was added in #221.

> Seems to upload before you click "upload"? The "upload" and "close" buttons seem to do the same thing?
Okay, what do you define as "upload"? I thought that upload would mean actually parsing the file and displaying it in the text area.

> Perhaps it would also be good to have two different modes: "append to currently loaded data" or "replace currently loaded data"?
I'll try adding that.

**Comment by jonorthwash** [comment]
What I'm concerned about with the upload and close buttons is that the file seems to be parsed and displayed in the text area as soon as it's selected with the file picker.  At that point, "upload" and "close" both just remove the modal and nothing else?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Really? I've tested it and that doesn't happen.

**Comment by JPJPJPOPOP** [comment]
Evidence:
importfile

**Comment by jonorthwash** [comment]
Hmm, it's not doing it now.  Perhaps I only imagined that behaviour... :|

It would be good to say how big the file is, and to make the progress bar display differently (e.g., pulse red or something) if it's bigger than allowed size.  And if we have append versus replace, then it should only allow replace if appending would be too big.

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Sure!

**Comment by JPJPJPOPOP** [comment]
@jonorthwash 

> it should only allow replace if appending would be too big.

Why would appending get too big?

**Comment by JPJPJPOPOP** [comment]
Woops accidentally closed.

**Comment by JPJPJPOPOP** [comment]
@jonorthwash @ftyers Please review. Thanks 😄

**Comment by jonorthwash** [comment]
Would be good to have "Remaining available space" in addition to "Total available space".  Or maybe "abc / xyz kB used" or "xyz kB total, abc kB available"?

What you've done so far is great though.

**Pull request merged**
