### PR TITLE
Fix table view deleting words

### LINKED ISSUE #326: table view return press deletes part of sentence
When pressing return in the table view to submit a change, half of the sentence/tree disappears.

### PR DESCRIPTION
**Pull request by diogoscf**
Fixes #326 
The problem was so simple to solve yet such a pain to figure out

### CODE REVIEW

**Comment by diogoscf** [comment]
Also sorry for the weird changes in bundle.js. It's my editor changing spacing for it to look better. The only actual change happens at line 12980

**Comment by keggsmurph21** [comment]
Nice! Also don't worry about diffs for compiled files like `bundle.js`: they will almost always be updated between commits.

**Comment by jonorthwash** [comment]
Uhm, so should @diogoscf be figuring out a way to fix this without modifying `bundle.js`?  Since we could get a new version of that any time, right?

**Comment by keggsmurph21** [comment]
Nope, modifying `bundle.js` is totally fine

**Comment by jonorthwash** [comment]
Oh, so the real change is in `table.js`, and `bundle.js` is generated from that?

**Comment by diogoscf** [comment]
Yes

**Comment by keggsmurph21** [comment]
exactly

**Comment by keggsmurph21** [comment]
in fact, almost every commit should change `bundle.js`. this could probably be accomplished automatically with some continuous integration tool, but it's not super important so long as someone compiles `bundle.js` when they make updates

**Comment by jonorthwash** [comment]
Okay, got it.  Thanks guys!

**Comment by jonorthwash** [comment]
It looks like after enter is pressed, table navigation ends.  Is this a regression, or was it always like this?

**Comment by diogoscf** [comment]
It was already like this

**Comment by jonorthwash** [comment]
> It looks like after enter is pressed, table navigation ends. Is this a regression, or was it always like this?

Actually, only when new information is entered, not when something is changed.

**Comment by jonorthwash** [comment]
> It was already like this

Okay, I think I'll this as another issue, and maybe GCI task.

**Pull request merged**
