### PR TITLE
Fix table view not showing dependencies

### LINKED ISSUE #331: Table view not updating after editing depencies
When dependencies are edited (in the graph or even directly on the table), the table doesn't update and subsequent changes to it will remove those edits. Also, nothing ever shows up on the deprel or head columns

### PR DESCRIPTION
**Pull request by diogoscf**
Fixes #331 
The object containing the sentence used to create the table does not contain keys the function assumed it did. This allows for proper usage of the table for editing the `HEAD`, `DEPREL` and `DEPS` columns

### CODE REVIEW

**Comment by jonorthwash** [comment]
This is working much better, but something still seems to be not right:

Collapsing a column of the table after text is entered in the column makes it "disappear" when the column is expanded again until new text is entered in one of the cells, in which case that text is added to the original text.  Additionally, the LEMMA column doesn't seem to collapse correctly, but does exhibit this same behaviour otherwise.

**Comment by jonorthwash** [comment]
Actually, various columns seem to decide not to collapse, not just LEMMA.

**Comment by diogoscf** [comment]
That was not caused by my code, but I’ll fix it.

**Comment by jonorthwash** [comment]
> That was not caused by my code, but I’ll fix it.

Yeah, don't worry about fixing the collapse problem (that's part of another task probably), but rather the disappearing text.  Disappearing text is a closely related issue to what you were doing, so it makes sense to fix it all at once.

**Comment by diogoscf** [comment]
It was keeping the `column-hide` class after expansion on the `td`
Also *column

**Pull request merged**
