### PR TITLE
PR re Issue #255

### PR DESCRIPTION
**Pull request by keggsmurph21**
- fixes buggy edited text moving around
- known issue: if i'm editing node A and click to node B, edit node B and click to node C, then it will throw errors ... can be avoided by not editing consecutive nodes

### CODE REVIEW

**Comment by jonorthwash** [comment]
Issue #255.

**Comment by jonorthwash** [comment]
This does fix the behaviour in question, but also does away with type-to-complete POS tags.

**Comment by keggsmurph21** [comment]
fixed it .. see dd70e497020d932a123201fbbd95c1ab1c961e23

**Comment by jonorthwash** [comment]
Now when I click outside of the first POS entry box and it correctly gives me another, that other one gets "stuck".  I can't enter text into it, or click outside of it to make it go away.

**Pull request closed without merging**
